force-app/main/default/objects/Product2/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Dimension__c.field-meta.xml
<CustomField>
    <fullName>Dimension__c</fullName>
    <label>Dimension</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <formula>IMAGE(Image_URL__c, &quot;image&quot;, 150, 150)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductController.cls
public with sharing class ProductController {

    @AuraEnabled(cacheable=true)
    public static List<Product2> getAllProducts() {
        try {
            List<Product2> products = [SELECT Id, Name, Description, Image_URL__c FROM Product2];
            return products;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> getProducts(List<Id> productIds) {
        try {
            System.debug(productIds);
            return [SELECT Name, Description, Price__c, Color__c, Dimension__c, Image_URL__c FROM Product2 WHERE Id IN :productIds];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Product2 getProduct(Id productId) {
        try {
            return [SELECT Name, Description, Image__c, Color__c, Dimension__c, Price__c FROM Product2 WHERE Id = :productId LIMIT 1];
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}